name: Purge CDN

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Purge JS file
      uses: wei/curl@v1.1.1
      with:
        args: https://purge.jsdelivr.net/gh/logisticdesign/cookie-banner@1/dist/cookie-banner.min.js
    - name: Purge CSS file
      uses: wei/curl@v1.1.1
      with:
        args: https://purge.jsdelivr.net/gh/logisticdesign/cookie-banner@1/dist/cookie-banner.min.css
